seed: 0
# could go lower, but 1 second per request to avoid spamming
model:
  num_samples: 1
  max_attempts: 10
  delay: 1.0
  # https://ai.google.dev/gemini-api/docs/models/gemini#gemini-2.0-flash
  model: gemini-2.0-flash
  max_completion_tokens: 8192
  prompt_cost: 0.00250
  completion_cost: 0.01000

data:
  sample_size: 1000
  train_topic: COVID-19 Vaccines
  # train_path: /content/drive/MyDrive/Data/vaccine-frames/covid19/annotations-and-data/test.jsonl
  train_path: "C:/Users/maxwe/My Drive/Data/vaccine-frames/covid19/annotations-and-data/test.jsonl"
  # train_frames: /content/co-vax-frames-claims-topics/annotations/frames.json
  train_frames: "C:/Users/maxwe/My Drive/Data/co-vax-frames-claims-topics/annotations/frames.json"
  test_topic: "Climate Change"
  # not needed for SemEval datasets, leave empty
  test_path: "."

pred:
  # will automatically prefix with test topic / train topic / model
  prediction_path: "C:/Users/maxwe/My Drive/Artifacts/cross-topic-frames"
